DANS-KNAW/easy-deposit-ui

src/main/typescript/actions/authenticationActions.ts
src/main/typescript/components/Header.tsx
src/main/typescript/constants/clientRoutes.ts
src/main/typescript/middleware/userDetailsMiddleware.ts
src/main/typescript/reducers/authenticationReducer.ts
src/test/typescript/mockserver/user.ts
webpack/config.json

* Send authentication as params
* Use 'deposit' as homeRoute
* Use 'deposit-api' as api path

NO-EASY: Send authentication as params

---

package.json
src/main/typescript/constants/clientRoutes.ts
src/main/typescript/lib/config.ts
webpack/base.config.js
webpack/config.json

Since the paths to the UI have changed in #16, the startup script needs fixing as well. With this change, the dev-server will open the browser to the new 'home route'.

fix dev-server start command

---

src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/components/login/LoginPage.tsx

rather than doing manual composition of HOCs (and with that do some magic with types), I found we can also use the `compose` function. Note that the order of the arguments is important, they are applied _**right to left**_.

use compose when using multiple HOCs

---

src/main/typescript/lib/formComponents/DoiField.tsx

show the button whenever there is a value, not just when the DOI is also fetched: you might also receive it with the metadata...

fix bug in doi field/button

---

.travis.yml
package-lock.json
package.json
pom.xml
src/main/typescript/lib/metadata/AccessRight.ts
src/main/typescript/lib/metadata/Audience.ts
src/main/typescript/lib/metadata/Contributor.ts
src/main/typescript/lib/metadata/Date.ts
src/test/typescript/lib/metadata/AccessRight.spec.ts
src/test/typescript/lib/metadata/Audience.spec.ts
src/test/typescript/lib/metadata/Contributor.spec.ts
src/test/typescript/lib/metadata/Date.spec.ts
tsconfig.json

Introduces unit testing with Maven and Travis integration, as well as a first couple of tests.
For now, the aim of unit testing is to test the (de)conversion between external and internal JSON data.
More tests will come in consecutive pull requests

Introducing unit tests

---

package.json
webpack/dev.config.js
webpack/mockserver.config.js
webpack/prod.config.js

* fix the build scripts for the mockserver. It turned out that the new Webpack v4 (#39) didn't put the compiled `*.js` file in the right place, which caused the mockserver not to be started.
* replace the `--mode` flags with properties in the `(dev|prod).config.js` files.

Fix mockserver build

---

src/main/resources/css/login.css
src/main/typescript/components/login/EasyLogin.tsx
src/main/typescript/components/login/LoginCard.tsx
src/main/typescript/components/login/LoginPage.tsx
src/main/typescript/reducers/index.ts

Amendment on https://github.com/DANS-KNAW/easy-deposit-ui/pull/48.
**When applied it will**
* Split the login component into multiple smaller components
* Clean up unused or unnecessary `className`s
@lindareijnhoudt @jo-pol hope you like it...
**_browser_**
**_iPhone 5/SE_**

split EasyLogin into multiple components

---

src/main/resources/constants/licenses.json
src/main/resources/css/form.css
src/main/resources/css/styling.css
src/main/typescript/components/form/DepositFormPage.tsx
src/main/typescript/components/form/parts/DepositLicenseForm.tsx
src/main/typescript/components/form/parts/licenseAndAccess/AccessRightsField.tsx
src/main/typescript/components/form/parts/licenseAndAccess/LicenseField.tsx
src/main/typescript/components/overview/DepositTableRow.tsx
src/main/typescript/lib/formComponents/RadioChoices.tsx

Fixes EASY-1601
* replace the license dropdown with a multi tiered radio choice
_The depositor has chosen for CC-BY-4.0, saved and reloaded the deposit._
_When clicking on 'show more...', it will show the first 3 licenses (+ selected license if it is not contained)._
_When clicking again on 'show more...', it will show all licenses._
_The arrow before each license will lead to a new tab with the license._

EASY-1601: Multi tiered license agreement selection

---

src/main/resources/css/footer.css
src/main/typescript/components/Footer.tsx

Fixes EASY-1609
* Remove address lines
* Add telephone number as link
* Add Privacy Statement link
* Change all link-targets to the english version and https

EASY-1609: Add Privacy Statement Link to Footer

---

src/main/resources/css/form.css
src/main/typescript/components/form/FoldableCard.tsx
src/main/typescript/components/form/parts/ArchaeologySpecificMetadataForm.tsx
src/main/typescript/components/form/parts/BasicInformationForm.tsx
src/main/typescript/components/form/parts/DepositLicenseForm.tsx
src/main/typescript/components/form/parts/LicenseAndAccessForm.tsx
src/main/typescript/components/form/parts/MessageForDataManagerForm.tsx
src/main/typescript/components/form/parts/PrivacySensitiveDataForm.tsx
src/main/typescript/components/form/parts/TemporalAndSpatialCoverageForm.tsx
src/main/typescript/components/form/parts/UploadTypeForm.tsx
src/main/typescript/components/form/parts/basicInformation/DoiField.tsx
src/main/typescript/lib/formComponents/AddButton.tsx
src/main/typescript/lib/formComponents/ContributorFieldArray.tsx
src/main/typescript/lib/formComponents/DropDownFieldArray.tsx
src/main/typescript/lib/formComponents/FieldArrayHOC.tsx
src/main/typescript/lib/formComponents/FieldHOC.tsx
src/main/typescript/lib/formComponents/QualifiedSchemedTextFieldArray.tsx
src/main/typescript/lib/formComponents/RadioChoices.tsx
src/main/typescript/lib/formComponents/RelationFieldArrayElement.tsx
src/main/typescript/lib/formComponents/RemoveButton.tsx
src/main/typescript/lib/formComponents/SchemedBoxArray.tsx
src/main/typescript/lib/formComponents/SchemedDatePickerArray.tsx
src/main/typescript/lib/formComponents/SchemedPointArray.tsx
src/main/typescript/lib/formComponents/SchemedTextFieldArray.tsx
src/main/typescript/lib/formComponents/TextFieldArray.tsx

Fixes EASY-1615
* move the buttons outside the fields
* do some reformatting of the form (`div`s, `container`s, `row`s, etc.)

EASY-1615: Move red minus buttons next to the fields

---

src/main/resources/css/depositOverviewPage.css
src/main/typescript/actions/depositOverviewActions.ts
src/main/typescript/components/overview/DepositOverview.tsx
src/main/typescript/components/overview/DepositTableRow.tsx

Fixes EASY-1595
* make each row of the deposit overview table fully clickable

EASY-1595: Make each row of the deposit overview table fully clickable

---

src/main/resources/css/depositOverviewPage.css
src/main/typescript/components/overview/DepositOverview.tsx
src/main/typescript/components/overview/DepositTableRow.tsx

Follow-up on EASY-1595 and #68
When @vesaakerman and I were working on this issue before, we found that when the `onClick` event was placed on the whole row, and when clicking the delete button, the delete event would also trigger the 'enter deposit' event. Hence @vesaakerman made each **cell** clickable (with exception for the _action cell_), rather than the whole row. However, the solution we should taken back then is to catch the delete event in the callback and call [`.stopPropagation()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation).

EASY-1595: stop propagation on delete button to not enter the deposit as well

---

src/main/resources/css/form.css
src/main/typescript/components/form/parts/licenseAndAccess/AccessRightsField.tsx
src/main/typescript/lib/metadata/AccessRight.ts
src/main/typescript/lib/metadata/Metadata.ts
src/main/typescript/lib/user/user.ts
src/main/typescript/middleware/depositFormMiddleware.ts
src/main/typescript/model/UserDetails.ts
src/main/typescript/reducers/userReducer.ts
src/test/typescript/lib/metadata/AccessRight.spec.ts
src/test/typescript/lib/user/user.spec.ts
src/test/typescript/mockserver/metadata.ts
src/test/typescript/mockserver/user.ts

Fixes EASY-
* the group-access option wil no longer be shown
* the group property is dropped from AccessRights objects
* the groups property is dropped from UserDetails objects

EASY-1717 remove group-access

---

src/main/typescript/components/form/parts/licenseAndAccess/AccessRightsField.tsx

posthumous review of #81
Rationale: don't need `compose` anymore, since there is only 1 HOC to compose, whereas there were 2 before removing the code in #81.
@jo-pol @DANS-KNAW/easy for review

posthumous review of #81

---

src/main/typescript/components/overview/DepositTableHead.tsx
src/main/typescript/components/overview/DepositTableRow.tsx

The deposit overview table had a small red line on the right side of the table head. This was due to the background being set to `.bg-primary`, which is `color:red` in our definitions (_whether it is correct to make `.bg-primary` as `color:red` is a question for another day! I think that should be something like `.bg-danger`._). However, since the table head is overlayed with a gradient, we don't need the red background anymore.
Besides, the table has negative margins by default (thanks, Bootstrap!), so it looked somewhat odd on smaller screens, in comparison to the deposit form. Therefore I added to both the table head and table rows a `ml-0 and mr-0`, as it is supposed to be.

Fix table background

---

src/test/typescript/lib/metadata/Identifier.spec.ts
src/test/typescript/mockserver/db.ts
src/test/typescript/mockserver/metadata.ts

Fixes EASY-
* drop the prefix "doi:" from doi values,
problem was detected with https://github.com/DANS-KNAW/easy-deposit-api/pull/78#pullrequestreview-176660917
* 
* 

NO JIRA ISSUE: dropped prefix from doi values in test data

---

src/main/resources/constants/contributorRoles.json
src/main/resources/css/form.css
src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/components/form/Validation.ts
src/main/typescript/components/form/parts/BasicInformationForm.tsx
src/main/typescript/components/form/parts/DepositLicenseForm.tsx
src/main/typescript/components/form/parts/LicenseAndAccessForm.tsx
src/main/typescript/components/form/parts/PrivacySensitiveDataForm.tsx
src/main/typescript/lib/formComponents/ContributorFieldArray.tsx
src/main/typescript/lib/metadata/Contributor.ts
src/main/typescript/lib/metadata/Identifier.ts
src/main/typescript/lib/metadata/Metadata.ts
src/test/typescript/component/form/Validation.spec.ts
src/test/typescript/lib/metadata/Contributor.spec.ts
src/test/typescript/mockserver/metadata.ts

Fixes EASY-1767
* merge the creator/contributor fields
* add validation for the new contributor fields
* move general form validation to the root of the form (1 function, to keep all validation consistent and not mix 2 methods)

EASY-1767: merging Creator/Contributor fields

---

src/main/typescript/components/form/parts/fileUpload/overview/FilesTableHead.tsx

NO JIRA. Renamed the column header "Checksum" to "SHA-1 checksum". Even though @rvanheest rightly remarked that this column is probably not very informative to most users it needs to stay for the moment, as it is at least a way for the user to verify that the uploaded files were received correctly. For this purpose the checksum algorithm used is indispensable.
One line

NO JIRA. Renamed Checksum heading

---

src/main/resources/css/form.css
src/main/typescript/components/form/parts/licenseAndAccess/LicenseField.tsx

part of EASY-1718
* add a way to show less licenses when all licenses are shown
_before clicking_
_after clicking_

EASY-1718: show less licenses

---

src/main/typescript/components/overview/DepositOverview.tsx
src/main/typescript/components/overview/EmptyDepositTableRow.tsx

Fixes EASY-1824
* show a row with "_no deposits found_" when no deposits have been made by a depositor

EASY-1824: empty deposit table row

---

src/main/typescript/components/form/Validation.ts
src/main/typescript/components/form/parts/LicenseAndAccessForm.tsx
src/main/typescript/components/form/parts/licenseAndAccess/AccessRightsAndLicenseFields.tsx
src/main/typescript/components/form/parts/licenseAndAccess/AccessRightsField.tsx
src/main/typescript/components/form/parts/licenseAndAccess/LicenseField.tsx
src/main/typescript/lib/metadata/License.ts
src/main/typescript/lib/metadata/Metadata.ts

Fixes EASY-1718
* make the accessright and license fields dependent
_Starting with a pre-filled form, it all looks like it did before..._
_... you can still click the 'show more' button..._
_... as well as the 'show less' button._
_When choosing 'Restricted Access', you get the DANS license as the only choice._
_Every time you change the access right, the license gets reset._
_Please note that the red warning is only shown when you had already chosen a license before you changed the access right_
_When opening up a new deposit, no license can be chosen until you specify the access right_

EASY-1718: dependent accessright and license fields

---

src/main/typescript/components/form/parts/fileUpload/upload/FileUploader.tsx
src/test/typescript/mockserver/db.ts
src/test/typescript/mockserver/server.ts

Fixes EASY-1815
* post files to the correct URL (not with filename postfix, but to the root directory of the deposit)

EASY-1815: FileUpload posts to the correct URL

---

src/main/typescript/components/form/Validation.ts
src/main/typescript/components/form/parts/DepositLicenseForm.tsx
src/main/typescript/lib/metadata/License.ts
src/main/typescript/lib/metadata/Metadata.ts
src/test/typescript/mockserver/metadata.ts
src/test/typescript/mockserver/postman-calls.json

Fixes EASY-1820 rename: acceptLicenseAgreement --> acceptDepositAgreement
* 
* 
* 
See related PR

EASY-1820 rename: acceptLicenseAgreement --> acceptDepositAgreement

---

src/main/typescript/components/form/parts/fileUpload/upload/FileLoader.tsx
src/test/typescript/mockserver/server.ts

Fixes EASY-1848
* change the expected `200` response to a `201`, as is specified by the [API](https://dans-knaw.github.io/easy-deposit-api/api.html#/directory/post_deposit__id__file__dir_path_)

EASY-1848: file POST expects 201 instead of 200

---

src/main/typescript/components/Header.tsx
src/main/typescript/components/form/parts/fileUpload/overview/FilesTableRow.tsx
src/main/typescript/components/login/LoginCard.tsx
src/main/typescript/components/overview/DepositTableRow.tsx
src/main/typescript/components/overview/NewDepositButton.tsx

Fixes EASY-1850
* add a `type` parameter to every `<button>`
* make sure that every `<button>` has a `type` parameter listed first (just to be consistent and to have an easy search)

EASY-1850: make sure every <button> has a type parameter

---

src/main/typescript/actions/authenticationActions.ts
src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/components/form/parts/fileUpload/overview/FilesOverview.tsx
src/main/typescript/components/login/EasyLogin.tsx
src/main/typescript/components/login/Validation.ts
src/main/typescript/components/login/index.ts
src/main/typescript/components/overview/DepositOverview.tsx
src/main/typescript/constants/authenticationConstants.ts
src/main/typescript/middleware/rejectedRequestMiddleware.ts
src/main/typescript/model/FileInfo.ts
src/main/typescript/reducers/authenticationReducer.ts
src/main/typescript/reducers/fileOverviewReducer.ts
src/test/typescript/mockserver/server.ts

Fixes EASY-1854
* fix some broken stuff with error handling on the login page (now it shows the error messages again and in a better way)
* add a number of servlet endpoints to test for error responses from the server
* add a number of forgotten error displays to the UI
* have a refactored login form
* no more nested Bootstrap containers
* the form is now inside the card (which is better for rendering) rather than the other way around
* fix logout error handling
* add validation to the login form

EASY-1854: properly deal with 401 responses in login

---

doc/validation.md
src/main/typescript/components/form/Validation.ts
src/main/typescript/components/form/parts/BasicInformationForm.tsx
src/test/typescript/component/form/Validation.spec.ts

Fixes EASY-1915
* describe validation messages
* replace all occurrences of `organisation` with `organization`
* include `nonEmptyRole` in contributor validation

EASY-1915: describe validation messages

---

src/main/typescript/lib/metadata/AccessRight.ts
src/test/typescript/lib/metadata/AccessRight.spec.ts
src/test/typescript/mockserver/metadata.ts

Fixes EASY-1902
* flatten the external representation of metadata field `accessRights`
* _I left the internal representation untouched, because that form already is frightening complex_
See also https://github.com/DANS-KNAW/easy-deposit-api/pull/122

EASY-1902: flatten external representation of metadata field 'accessRights'

---

pom.xml

Fixes EASY-1871
* run `npm version` command to make the version in `package.json` conform to the version in `pom.xml`

EASY-1871: run 'npm version' command to make package.json version conform to the version in pom.xml

---

src/main/resources/constants/contributorIds.json
src/main/typescript/lib/dropdown/dropdown.ts
src/main/typescript/lib/formComponents/ContributorFieldArray.tsx
src/main/typescript/model/DropdownLists.ts
src/test/typescript/component/form/Validation.spec.ts

Fixes EASY-2020
* fix the regex patterns for checking the validity of the contributor identifiers
* add placeholders with examples for every type of contributor identifier (see examples below)

EASY-2020: proper regex patterns for contributorIds

---

src/main/typescript/actions/authenticationActions.ts
src/main/typescript/actions/configurationActions.ts
src/main/typescript/actions/depositFormActions.ts
src/main/typescript/actions/depositOverviewActions.ts
src/main/typescript/actions/dropdownActions.ts
src/main/typescript/actions/fileOverviewActions.ts
src/main/typescript/actions/helpTextActions.ts
src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/components/overview/DepositOverview.tsx
src/main/typescript/lib/fetch.ts

Fixes EASY-1843
* display a proper error message when `easy-deposit-api` is temporarily unavailable

EASY-1843: proper error message when backend service is unavailable

---

src/main/typescript/components/form/parts/UploadTypeForm.tsx
src/main/typescript/lib/formComponents/RadioChoices.tsx

Fixes EASY-2053
* fix the CLARIN metadata radio button

EASY-2053: contains CLARIN metadata radio button disappears after trying to select option

---

src/main/resources/css/depositOverviewPage.css

Fixes EASY-2066
* revert a bit of https://github.com/DANS-KNAW/easy-deposit-ui/pull/132 to make the 'reload' icons in error bars not be too big.

EASY-2066: reintroduce icon css to make reload icon smaller

---

src/main/typescript/components/Paginationable.tsx
src/main/typescript/components/form/parts/fileUpload/overview/FilesOverview.tsx
src/main/typescript/components/overview/DepositOverview.tsx

* not say '_entries_' in the pagination component anymore, but rather '_deposits_' or '_files_', depending on the usage
@janvanmansum this is as discussed during our meeting

replace 'entries' by 'deposits'/'files' in pagination component and usages

---

src/main/typescript/components/form/parts/fileUpload/overview/FilesTableRow.tsx

Fixes EASY-2075
* wrap `fullpath` in a `<div>` to always put `confirmButtons` on new line

EASY-2075: put confirm button always on new line

---

src/main/typescript/components/Paginationable.tsx

Fixes EASY-2074
* no longer show entry counters on an empty table
* recover from invalid state

EASY-2074: don't show entry counters on an empty table

---

src/main/resources/constants/dcmiTypes.json

Make `dcmiType` keywords compliant with http://dublincore.org/schemas/xmls/qdc/2008/02/11/dcmitype.xsd.

fix keywords of dcmiTypes

---

src/main/typescript/lib/metadata/License.ts
src/test/typescript/lib/metadata/License.spec.ts
src/test/typescript/mockserver/metadata.ts

Fixes EASY-2101
* no longer accept the license as a `String`, but rather as a `SchemedValue`

EASY-2101: license field as schemed value

---

src/main/typescript/components/form/parts/fileUpload/upload/FileLoader.tsx

Cancel a file upload that is still in progress when leaving the deposit form page.

cancel file upload on leaving page

---

src/main/resources/css/dansColors.css
src/main/typescript/actions/fileUploadActions.ts
src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/components/form/parts/fileUpload/upload/FileUploader.tsx
src/main/typescript/constants/fileUploadConstants.ts
src/main/typescript/model/AppState.ts
src/main/typescript/model/FileUploadState.ts
src/main/typescript/reducers/fileUploadReducer.ts
src/main/typescript/reducers/index.ts
src/main/typescript/selectors/fileUploadSelectors.ts

Fixes EASY-2080
* store global state (in Redux) on whether a file is being uploaded right now
* disable the `save` and `submit` buttons when a file is being uploaded right now
* disable the `upload file` button when saving or submitting (as suggested by @jo-pol)

EASY-2080: disable submit/save buttons while uploading a file

---

src/main/resources/constants/spatialCoordinates.json

Fixes EASY-2107
* swap the ranges of `x-min`/`y-min` and `x-max`/`y-max`

EASY-2107: fix ranges for spatialCoordinates

---

src/main/resources/css/depositOverviewPage.css
src/main/typescript/components/overview/DepositTableRow.tsx
src/test/typescript/mockserver/deposit.ts

Fixes EASY-2098
* render newlines in the deposit overview state description
**before:**
**after:**

EASY-2098: newline wrapping of deposit overview state description

---

src/main/typescript/components/Paginationable.tsx

Fixes EASY-2106
* recalculate the start index on change in `entriesPerPage`
* some refactorings and inlining
@rkruithof I could not reproduce the decimal number examples you showed in the issue, but I fixed the `startIndex` recalculation. Example:
In the tables below we go from `old state` (10 elements per page) to `new state` (20 elements per page). If you go from `old state` page 1, to `new state`, we want to end up on page 0. `old state` page 5 ends up in `new state` on page 2. etcetera...
`elements per page = 10 (old state)`
page number | start index | end index
-------------:|-----------:|---------:
0 | 0 | 9
1 | 10 | 19
2 | 20 | 29
3 | 30 | 39
4 | 40 | 49
5 | 50 | 59
6 | 60 | 69
7 | 70 | 79
`elements per page = 20 (new state)`
page number | start index | …

EASY-2106: deposit-overview page numbers can take non-integer values

---

src/main/typescript/Routes.tsx
src/main/typescript/components/Header.tsx
src/main/typescript/components/SignoutPage.tsx
src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/constants/clientRoutes.ts

Fixes EASY-2087
* make some errors on the deposit form more specific (_not related to the actual issue_)
* implement signout routing as an alternative to 'onClick' after a 'Prompt OK'
The `<Prompt/>` that causes the warning about an unsaved form blocks the routing that is done via react-router, but does not prevent an `onClick` event on the `<Link/>` (in the header) from happening, as we currently do in the `<Header/>` component. Instead, the `log out` link now goes to a different page, that does the `signout` procedure with the server and then reroutes to 'home', as the original `<Link/>` did.

EASY-2087: "log out" with dirty deposit-form causes confirmation prompt, but logs out regardless of choice

---

src/main/resources/css/depositOverviewPage.css
src/main/typescript/components/overview/DepositTableRow.tsx
src/test/typescript/mockserver/deposit.ts

* render deposit descriptions with HTML tags as such; concretely renders `<a/>` tags properly and makes them clickable
* https://github.com/DANS-KNAW/easy-deposit-api/pull/164
* https://github.com/DANS-KNAW/easy-deposit-api/pull/161/files?file-filters%5B%5D=.properties&file-filters%5B%5D=.scala#r296196986

make <a/> tags in deposit description clickable

---

src/main/resources/css/helptext.css
src/main/resources/helptexts/privacySensitiveDataPresent.html
src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/components/form/parts/LicenseAndAccessForm.tsx
src/main/typescript/components/form/parts/PrivacySensitiveDataForm.tsx
src/main/typescript/components/form/parts/licenseAndAccess/AccessRightsAndLicenseFields.tsx
src/main/typescript/components/form/parts/licenseAndAccess/AccessRightsField.tsx
src/main/typescript/lib/formComponents/RadioChoices.tsx
src/main/typescript/lib/metadata/Metadata.ts
src/test/typescript/lib/metadata/Metadata.spec.ts

Fixes EASY-2135
* Move the 'Personal data' card up to the top of the metadata cards
* When `Yes, this dataset does contain personal data` is clicked:
* Access right option `Open Access` will be disabled
* Access right option `Restricted Access` will be selected
* License `DANS LICENSE` will be selected
* When `No, this dataset does not contain personal data` is clicked:
* Access right option `Open Access` will be selected (and re-enabled if it was disabled before)
* No license will yet be selected by default; the user can decide on the license on its own
* _After discussion with Marjan, this turned out to be the case. I added the default in fa1a23b._
* _Discussed this with Marjan. She sent me a new version of this help text, which was added in 15a812d._
_New …

EASY-2135: connection between access right and personal data field

---

src/main/typescript/lib/metadata/Metadata.ts
src/test/typescript/mockserver/metadata.ts

Fixes EASY-2250
* no longer split `description`, `source` and `instructionsForReuse` on newlines on save in `deposit-api`

EASY-2250: don't split description, source and instructionsForReuse on newlines

---

src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/lib/user/user.ts
src/test/typescript/lib/user/user.spec.ts
src/test/typescript/mockserver/user.ts

Fixes EASY-2257 : use display name to show the same value as in webui
* 
* 
* 
* don't use users predefined with dtap: create a new user on the easy-webui of deasy
* login, not the user name in the toolbar
* go to deposits
* the toolbar should show the same user name
* use variations with and without initials
* use ldap (apache directory studia) for variations with/without givenName and/or initials
https://github.com/DANS-KNAW/easy-deposit-api/pull/172 should be merged/deployed first

EASY-2257 : use display name to show the same value as in webui

---

webpack/base.config.js

Fixes EASY-1975
* add configuration.json back into the build output

EASY-1975: add configuration.json back into the build output

---

pom.xml

Fixes EASY-2431
* Turn on an rpm switch that makes malencoded metadata a warning instead of an error.
* For details see: https://github.com/rpm-software-management/rpm/issues/952#issuecomment-558618524

EASY-2431 easy-deposit-ui RPM-build faalt met rpm versie 4.15.1

---

src/main/typescript/components/form/Validation.ts
src/main/typescript/lib/formComponents/RelationFieldArrayElement.tsx
src/test/typescript/component/form/Validation.spec.ts

Fixes EASY-2430
* only allow http(s) URLs in relation field

EASY-2430: only allow http(s) URLs in relation field

---

src/main/typescript/components/form/Validation.ts
src/test/typescript/component/form/Validation.spec.ts

Fixes EASY-2849
* make scheme on related identifier optional
This change causes the 'scheme' in the related identifier to be optional. Not choosing a scheme leads to a `<dcterms:relation>...</dcterms:relation>` field in DDM and a `<emd:relation><dc:relation>...</dc:relation></emd:relation>` field in EMD. It is displayed in EASY as 

EASY-2489: make scheme on related identifier optional

---

src/main/typescript/components/form/Validation.ts
src/test/typescript/component/form/Validation.spec.ts

Fixes EASY-2488
* add extra validation for spatial box values: `north` must be greater than `south` and `east` must be greater than `west`

EASY-2488: extra validation for spatial box values

---

src/main/typescript/components/form/parts/BasicInformationForm.tsx

Fixes EASY-2493
* hide the 'instructions for reuse' field

EASY-2493: hide 'instructions for reuse' field

---

package-lock.json
package.json
webpack/base.config.js
webpack/prod.config.js

Fixes EASY-2505
_The behavior described in the issue is caused by the browser caching the HTML file._
* use `[contenthash]` rather than `[chunkhash]` in the filenames of the compiled JS files
* use `[contenthash]` in the filenames of the compiled CSS files
* use `OptimizeCssAssetsPlugin` in the `minimize` step
@janvanmansum the Apache config we produced before is not necessary. The HTML file is different after a deploy of a new version because of the `contenthash` in the CSS and JS files. Hence a `200` with the new content is sent on first entrance after a deploy; a `304` is sent (with use of the browser cache) on other occasions.

EASY-2505: avoid browser caching

---

src/main/resources/constants/abrPeriodeTemporals.json

Fixes EASY-2533
* fix typo: `PALEOB` to `PALEOLB`

EASY-2533: fix typo in PALEOB --> PALEOLB

---

package-lock.json
src/main/resources/constants/identifiers.json
src/main/typescript/components/form/Validation.ts
src/main/typescript/components/form/parts/BasicInformationForm.tsx
src/main/typescript/components/form/parts/basicInformation/AlternativeIdentifierFieldArray.tsx
src/main/typescript/components/form/parts/basicInformation/RelatedIdentifierFieldArray.tsx
src/main/typescript/lib/metadata/Identifier.ts
src/main/typescript/lib/metadata/Metadata.ts
src/main/typescript/lib/metadata/Relation.ts
src/main/typescript/lib/metadata/Value.ts
src/test/typescript/component/form/Validation.spec.ts
src/test/typescript/lib/metadata/Metadata.spec.ts

Fixes EASY-2582
* add support for 'other' related/alternative identifiers
**In the form:**
**In DDM:**
```xml
<ddm:references scheme="id-type:DOI" href="https://doi.org/10.17026/test-doi-related-identifier">10.17026/test-doi-related-identifier</ddm:references>
<ddm:replaces scheme="id-type:URN" href="http://persistent-identifier.nl/urn:nbn:nl:ui:test-urn-related-identifier">
urn:nbn:nl:ui:test-urn-related-identifier
</ddm:replaces>
<dcterms:requires xsi:type="id-type:ISBN">my-isbn-related-identifier</dcterms:requires>
<dcterms:hasVersion xsi:type="id-type:ISSN">my-issn-related-identifier</dcterms:hasVersion>
<dcterms:isFormatOf xsi:type="id-type:NWO-PROJECTNR">my-nwo-related-identifier</dcterms:isFormatOf>
<dcterms:isPartOf>my own related …
```

EASY-2582: add support for other related/alternative identifier

---

src/main/typescript/lib/formComponents/ContributorFieldArray.tsx

~Fixes EASY-~
* make the placeholders in the creator/contributor fields less confusing
This was done after we had multiple complaints from depositors who couldn't see the difference between the placeholders and the real text.

less confusing placeholders

---

src/main/typescript/lib/metadata/Contributor.ts

Fixes EASY-2641: ISNI regexp allowed too many digits if last was X
* 
* 
* 
* with the old ui: try to submit a new deposit with `http://isni.org/isni/00000001210326839X`
* it will fail and highlight the ISNI, remove the `9` and the highlight disappears
* build, deploy, refresh
* you now will have to remove `39` to make the highlight disappear
When released before https://github.com/DANS-KNAW/easy-schema/pull/80
a normal ui/ingest cycle can no longer test that validate-dans-bag rejects a too long ISNI

EASY-2641: ISNI regexp allowed too many digits if the last is X

---

src/main/resources/helptexts/contributors.html
src/main/typescript/lib/formComponents/ContributorFieldArray.tsx

Fixes EASY-2665
* Remove mandatory-indicators from initials and surname
* Add smaller examples to contributor helptext

EASY-2665: Add smaller examples to contributor helptext

---

src/main/typescript/components/form/parts/fileUpload/upload/FileUploader.tsx

Fixes EASY-2619 + EASY-2513: large tar, error handling
* render upload error messages as HTML
* 
* 
See related pull request
required by https://github.com/DANS-KNAW/easy-deposit-api/pull/213

EASY-2619 + EASY-2513: large tar, error handling

---

src/main/typescript/components/form/Validation.tsx
src/test/typescript/component/form/Validation.spec.ts

Fixes EASY-2685
* add non-blank checks before validating person identifiers

EASY-2685: add non-blank checks before validating person identifiers
