DANS-KNAW/easy-deposit-ui

.travis.yml
README.md
package.json
pom.xml
webpack/dev.config.js
webpack/prod.config.js

Some additional stuff for the general project setup.
* port `8080` is already used by the VM, so that would conflict eventually
* using host `000.000.00.00` you can also connect from a different device on the same network

Further project setup

---

package-lock.json
package.json
src/main/typescript/components/Footer.tsx
src/main/typescript/lib/config.ts
webpack/base.config.js

Fixes no EASY issue
* calculate the build date on build time in Webpack
* declare and use the build date in the footer

build date in footer

---

pom.xml

NO JIRA.
* Change the context root of the applicaton (when installed with RPM) to `/deposit`.
`pom.xml`

Changed the context root to /deposit

---

src/main/resources/css/foldable.css
src/main/typescript/components/form/FoldableCard.tsx

fix a bug with the layout of the cards in the deposit form. Everything still looks the same, but only the details in the implementation changed.

bugfix card

---

src/main/typescript/middleware/depositFormMiddleware.ts
src/main/typescript/model/Authentication.ts
src/test/typescript/mockserver/metadata.ts

More fixing of the metadata conversion
@DANS-KNAW/easy for merge

fix metadata conversion

---

src/main/typescript/actions/authenticationActions.ts
src/main/typescript/actions/depositFormActions.ts
src/main/typescript/actions/depositOverviewActions.ts
src/main/typescript/actions/userActions.ts

NO EASY
* Remove wait time for simulating api-calls
* 
*

Remove wait time for simulating api-calls

---

src/main/typescript/constants/apiConstants.ts
src/main/typescript/middleware/depositMiddleware.ts
src/test/typescript/mockserver/db.ts
src/test/typescript/mockserver/deposit.ts
src/test/typescript/mockserver/postman-calls.json
src/test/typescript/mockserver/server.ts

Changes according to https://github.com/DANS-KNAW/easy-deposit-api/pull/37

state_description -> stateDescription

---

src/main/resources/application.json

* Remove the dummy entry from `application.json`.
Requires https://github.com/DANS-KNAW/easy-dtap/pull/211

NO JIRA. Get rid of dummy entry in easy-deposit-ui config

---

src/main/typescript/components/form/parts/ArchaeologySpecificMetadataForm.tsx
src/main/typescript/components/form/parts/BasicInformationForm.tsx
src/main/typescript/components/form/parts/LicenseAndAccessForm.tsx
src/main/typescript/components/form/parts/TemporalAndSpatialCoverageForm.tsx
src/main/typescript/components/form/parts/UploadTypeForm.tsx
src/main/typescript/lib/metadata/Identifier.ts
src/main/typescript/lib/metadata/Language.ts
src/main/typescript/lib/metadata/SpatialCoverage.ts

Fixes EASY-1552
* refactor form part `Component`s to functional components
* fix validation bug with Clarin metadata
* fix conversion bug
* remove unnecessary calls to `clean`

EASY-1552 Refactorings and bugfixes

---

src/main/typescript/lib/metadata/Format.ts
src/main/typescript/lib/metadata/Language.ts
src/main/typescript/lib/metadata/License.ts
src/main/typescript/middleware/depositFormMiddleware.ts
src/test/typescript/lib/metadata/Format.spec.ts
src/test/typescript/lib/metadata/Identifier.spec.ts
src/test/typescript/lib/metadata/Language.spec.ts
src/test/typescript/lib/metadata/License.spec.ts

Part of EASY-1580
* add unit tests for

EASY-1580: unit-testing some more conversions

---

src/main/resources/css/form.css
src/main/typescript/components/form/parts/BasicInformationForm.tsx
src/main/typescript/components/form/parts/basicInformation/DateFieldArray.tsx
src/main/typescript/components/form/parts/basicInformation/IsoDateFieldArray.tsx
src/main/typescript/lib/formComponents/DatePickerField.tsx
src/main/typescript/lib/formComponents/SchemedDatePickerArray.tsx

Fixes EASY-1569
* implement the 'Date (ISO 8601)' field

EASY-1569: Implement date field with dropdown

---

src/main/typescript/components/Footer.tsx

Footer refactored

---

src/main/typescript/components/Header.tsx
src/main/typescript/constants/clientRoutes.ts

EASY-1592: remove register link from navbar

---

src/main/typescript/actions/authenticationActions.ts

EASY-1594: Use form-data instead of params for login

---

src/main/typescript/middleware/depositMiddleware.ts
src/test/typescript/mockserver/db.ts

Fixes EASY-1596
* Insert "Untitled deposit" as the title if no title received from the server.

EASY-1596 Display 'Unitled deposit' if no title is provided

---

src/main/resources/css/login.css
src/main/typescript/components/login/EasyLogin.tsx
src/main/typescript/components/login/LoginCard.tsx
src/main/typescript/components/login/LoginPage.tsx
src/main/typescript/reducers/index.ts

Fixes EASY-1593
* Add column-layout
* Apply card-layout
* autoFocus

EASY-1593: Improve login layout

---

src/main/resources/constants/identifiers.json
src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/components/form/parts/BasicInformationForm.tsx
src/main/typescript/components/form/parts/basicInformation/AlternativeIdentifierFieldArray.tsx
src/main/typescript/components/form/parts/basicInformation/RelatedIdentifierFieldArray.tsx
src/main/typescript/lib/formComponents/FieldArrayHOC.tsx
src/main/typescript/lib/formComponents/FieldHOC.tsx
src/main/typescript/lib/formComponents/QualifiedSchemedTextFieldArray.tsx
src/main/typescript/lib/formComponents/RelationFieldArrayElement.tsx
src/main/typescript/lib/formComponents/RepeatableField.ts
src/main/typescript/lib/formComponents/SchemedDatePickerArray.tsx
src/main/typescript/lib/formComponents/SchemedTextFieldArray.tsx

Fixes EASY-1572
* implement the related identifier fields

EASY-1572: Implement related identifier field

---

src/main/typescript/components/login/EasyLogin.tsx

Make pwd field starred

---

src/main/typescript/client.tsx
src/main/typescript/lib/config.ts
src/main/typescript/lib/metadata/Contributor.ts
src/main/typescript/lib/metadata/Format.ts
src/main/typescript/lib/metadata/Identifier.ts
src/main/typescript/lib/metadata/Language.ts
src/main/typescript/lib/metadata/Relation.ts
src/main/typescript/lib/metadata/SpatialCoverage.ts
src/main/typescript/lib/metadata/TemporalCoverage.ts
src/main/typescript/lib/metadata/Type.ts
src/main/typescript/lib/metadata/misc.ts
src/main/typescript/reducers/index.ts
src/main/typescript/store.ts
tsconfig.json

Some random stuff for the workshop

Some final prep for the Redux workshop

---

src/main/typescript/lib/config.ts
src/main/typescript/lib/metadata/Contributor.ts
src/main/typescript/lib/metadata/Format.ts
src/main/typescript/lib/metadata/Identifier.ts
src/main/typescript/lib/metadata/Language.ts
src/main/typescript/lib/metadata/SpatialCoverage.ts
src/main/typescript/lib/metadata/TemporalCoverage.ts
src/main/typescript/lib/metadata/Type.ts
src/main/typescript/lib/metadata/misc.ts
src/main/typescript/reducers/index.ts
tsconfig.json

This reverts commit 66c715c207d04a7991d08409dda2383202f97d9a.
Fixing module:commonjs bug from previous PR

Fixing module:commonjs bug from previous PR

---

src/main/typescript/actions/dropdownActions.ts
src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/components/form/DepositFormPage.tsx
src/main/typescript/components/form/parts/FileUpload.tsx
src/main/typescript/components/form/parts/fileUpload/overview/FilesOverview.tsx
src/main/typescript/lib/formComponents/ContributorFieldArray.tsx
src/main/typescript/lib/redux.ts

Fixes EASY-1599
* fix race condition between fetching dropdown data and deposit metadata
* only fetch dropdown data when it is not yet fetched
* move some file loading functions to their intended place (solved TODOs)
* fix an incorrectly placed `<Mandatory/>` star (*) in the contributor field

EASY-1599: fix race condition between fetching dropdown data and deposit metadata

---

src/main/typescript/components/form/parts/ArchaeologySpecificMetadataForm.tsx
src/main/typescript/components/form/parts/BasicInformationForm.tsx
src/main/typescript/components/form/parts/LicenseAndAccessForm.tsx
src/main/typescript/components/form/parts/TemporalAndSpatialCoverageForm.tsx
src/main/typescript/components/form/parts/UploadTypeForm.tsx
src/main/typescript/components/form/parts/archaeologySpecificMetadata/AbrComplexSubjectFieldArray.tsx
src/main/typescript/components/form/parts/archaeologySpecificMetadata/AbrPeriodeTemporalsFieldArray.tsx
src/main/typescript/components/form/parts/basicInformation/AlternativeIdentifierFieldArray.tsx
src/main/typescript/components/form/parts/basicInformation/AudienceFieldArray.tsx
src/main/typescript/components/form/parts/basicInformation/ContributorFields.tsx
src/main/typescript/components/form/parts/basicInformation/DateFieldArray.tsx
src/main/typescript/components/form/parts/basicInformation/IsoDateFieldArray.tsx
src/main/typescript/components/form/parts/basicInformation/LanguageField.tsx
src/main/typescript/components/form/parts/basicInformation/LanguageFieldArray.tsx
src/main/typescript/components/form/parts/basicInformation/RelatedIdentifierFieldArray.tsx
src/main/typescript/components/form/parts/basicInformation/RelationFieldArray.tsx
src/main/typescript/components/form/parts/licenseAndAccess/LicenseField.tsx
src/main/typescript/components/form/parts/licenseAndAccess/RightsholderFields.tsx
src/main/typescript/components/form/parts/temporalAndSpatialCoverage/SpatialBoxFieldArray.tsx
src/main/typescript/components/form/parts/temporalAndSpatialCoverage/SpatialCoverageIso3166FieldArray.tsx
src/main/typescript/components/form/parts/temporalAndSpatialCoverage/SpatialPointFieldArray.tsx
src/main/typescript/components/form/parts/uploadType/DcmiTypesFieldArray.tsx
src/main/typescript/components/form/parts/uploadType/ImtFormatsFieldArray.tsx
src/main/typescript/lib/formComponents/ContributorFieldArray.tsx
src/main/typescript/lib/formComponents/ReduxFormUtils.ts

Fixes EASY-1637
* fix rendering of the ContributorFields
* make other uses of dropdown data consistent with it

EASY-1637: fix rendering of the ContributorFields

---

src/main/resources/css/form.css
webpack/base.config.js
webpack/prod.config.js

Fixes EASY-1587
* split production build into 2 *.js files

EASY-1587: split production build into 2 *.js files

---

src/main/typescript/actions/dropdownActions.ts

Fixes EASY-1728
* fix the race condition between fetching dropdown data and the form's metadata

EASY-1728: Race condition between fetching dropdowns and metadata

---

src/main/resources/css/dansColors.css
src/main/resources/css/depositOverviewPage.css
src/main/resources/css/foldable.css
src/main/resources/css/form.css
src/main/typescript/components/form/FoldableCard.tsx

Some review and extra styling for https://github.com/DANS-KNAW/easy-deposit-ui/pull/87
@lindareijnhoudt see the individual commits and messages for details on refactorings.
Listed below are screenshots of a couple more styling improvements I made in this PR as well.
**_+/- and validate button styling_**
* first _validate_ button normal
* second _validate_ button disabled
* third _validate_ button on `hover`
**_card headers_**
* the header was smaller than the `required` text, so I switched them around in styling
* 👍 for the gradient background you introduced!

Css review

---

src/main/resources/css/dansColors.css
src/main/resources/css/form.css

* better gradients for red and green buttons on hover
* fix borders and disabled properties
_delete file button on hover_
_delete field button on hover_
_delete field button disabled_
_add field button on hover_

improve button gradients and borders

---

src/main/typescript/actions/fileOverviewActions.ts
src/main/typescript/reducers/fileOverviewReducer.ts

don't update local files list on DELETE, but do a GET /files instead

don't update local files list on DELETE, but do a GET /files instead

---

src/main/resources/css/dansColors.css
src/main/resources/css/form.css
src/main/resources/helptexts/doi.html
src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/components/form/Validation.ts
src/main/typescript/components/form/parts/BasicInformationForm.tsx
src/main/typescript/components/form/parts/DepositLicenseForm.tsx
src/main/typescript/components/form/parts/LicenseAndAccessForm.tsx
src/main/typescript/components/form/parts/PrivacySensitiveDataForm.tsx
src/main/typescript/components/form/parts/basicInformation/DoiField.tsx
src/main/typescript/components/form/parts/licenseAndAccess/AccessRightsField.tsx
src/main/typescript/components/form/parts/licenseAndAccess/LicenseField.tsx
src/main/typescript/lib/formComponents/Checkbox.tsx
src/main/typescript/lib/formComponents/DatePickerField.tsx
src/main/typescript/lib/formComponents/DropDownField.tsx
src/main/typescript/lib/formComponents/DropDownFieldArray.tsx
src/main/typescript/lib/formComponents/FieldArrayHOC.tsx
src/main/typescript/lib/formComponents/FieldHOC.tsx
src/main/typescript/lib/formComponents/Mandatory.tsx
src/main/typescript/lib/formComponents/RadioChoices.tsx
src/main/typescript/lib/formComponents/TextFieldArray.tsx
src/main/typescript/model/DepositForm.ts
src/main/typescript/model/FileInfo.ts
src/main/typescript/reducers/depositFormReducer.ts
src/test/typescript/component/form/Validation.spec.ts

EASY-1556: Validation in metadata form

---

src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/components/form/parts/DepositLicenseForm.tsx
src/main/typescript/lib/metadata/Metadata.ts

NO JIRA
* Update the terminology with respect to the depositor agreement.

NO JIRA. Changed Deposit license to Deposit agreement.

---

src/main/typescript/components/form/parts/fileUpload/overview/FilesTableRow.tsx
src/main/typescript/lib/files/files.ts
src/main/typescript/model/FileInfo.ts
src/test/typescript/lib/files/files.spec.ts
src/test/typescript/mockserver/db.ts
src/test/typescript/mockserver/fileinfo.ts
src/test/typescript/mockserver/server.ts

Part of EASY-1815
* fix file path display
* fix removal in subfolder

EASY-1815: fix file path display and removal in subfolder

---

src/main/typescript/components/form/parts/BasicInformationForm.tsx

remove helpText attribute from relations field such that it doesn't try to fetch this text no more

remove helpText attribute from relations field

---

src/main/resources/constants/audiences.json

Fixes EASY-1840
easy-schema                      | [PR#68](https://github.com/DANS-KNAW/easy-schema/pull/68)     | ..

EASY-1840: Change label of D21300 to 'Biochemistry, molecular biology'

---

src/main/typescript/components/form/parts/LicenseAndAccessForm.tsx
src/main/typescript/lib/metadata/Contributor.ts
src/main/typescript/lib/metadata/Metadata.ts

Fixes EASY-1900
* fix rightsholder to general contributor conversion

EASY-1900: fix rightsholder to general contributor conversion

---

src/main/typescript/actions/authenticationActions.ts
src/main/typescript/components/form/Validation.ts
src/test/typescript/component/form/Validation.spec.ts

Fixes EASY-1909
* capitalize sentence

EASY-1909: capitalize sentence

---

src/main/typescript/components/Header.tsx

login -> log in

---

src/main/resources/css/depositOverviewPage.css
src/main/typescript/components/overview/DepositOverview.tsx
src/main/typescript/components/overview/DepositTableRow.tsx

~~Fixes EASY-~~
* add links to deposit overview table rows

add links to deposit overview table rows

---

src/main/resources/css/footer.css
src/main/typescript/components/form/parts/LicenseAndAccessForm.tsx

* correct color on hover of a link in the footer
* Mark rightsholder as a mandatory field

Minor changes

---

src/main/resources/constants/contributorIds.json
src/main/typescript/actions/dropdownActions.ts
src/main/typescript/components/form/Validation.ts
src/main/typescript/components/form/parts/basicInformation/ContributorFields.tsx
src/main/typescript/lib/dropdown/dropdown.ts
src/main/typescript/lib/formComponents/ContributorFieldArray.tsx
src/main/typescript/model/DropdownLists.ts
src/test/typescript/component/form/Validation.spec.ts
src/test/typescript/lib/metadata/Metadata.spec.ts

Fixes EASY-1931
* validate contributorIds (ORCID, ISNI, DAI)

EASY-1931: validate contributorIds (ORCID, ISNI, DAI)

---

pom.xml
src/main/resources/css/depositOverviewPage.css
src/main/resources/css/filesOverviewTable.css

Fixes EASY-2036
* correctly position the 'wait' and 'trash' icons

EASY-2036: positioning of wait and trash icons

---

src/main/typescript/components/form/parts/BasicInformationForm.tsx
src/main/typescript/components/form/parts/basicInformation/AudienceFieldArray.tsx

Fixes EASY-2048
* fix a bug where a new audience field was created with an incorrect type

EASY-2048: new audience field with proper type

---

src/main/typescript/reducers/depositOverviewReducer.ts
src/main/typescript/reducers/fileOverviewReducer.ts

Fixes EASY-2076
* fix the cancellation of deletes in deposit overview and file overview

EASY-2076: fix delete cancellation in reducers of deposit overview and file overview

---

src/main/typescript/CookieAuth.tsx
src/main/typescript/actions/authenticationActions.ts
src/main/typescript/client.tsx
src/test/typescript/mockserver/server.ts

Fixes EASY-2061
* attempt to login using the available cookies

EASY-2061: try to login with a cookie

---

src/main/resources/css/fileLoader.css
src/main/typescript/components/form/parts/fileUpload/upload/FileLoader.tsx

Part of EASY-2068
don't show cancel button while an upload is 'processing', as requested by @jo-pol.

EASY-2068: no cancel button on processing

---

src/main/typescript/lib/formComponents/DatePickerField.tsx

Fixes EASY-2108
* discard any time came with the chosen date

EASY-2108: remove time from chosen date

---

src/main/typescript/lib/metadata/License.ts
src/test/typescript/lib/metadata/License.spec.ts
src/test/typescript/mockserver/metadata.ts

fixes EASY-2114
* add license 'DANS general conditions of use'

EASY-2114: add license 'DANS general conditions of use'

---

src/main/typescript/components/form/DepositForm.tsx

Fixes EASY-2086
* disable native form validation

EASY-2086: disable native form validation

---

src/main/typescript/components/Paginationable.tsx

As suggested by @rkruithof, I added first and last page numbers in the pagination when appropriate.

Pagination with first and last page when appropriate

---

src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/components/form/parts/PrivacySensitiveDataForm.tsx
src/main/typescript/components/form/parts/TemporalAndSpatialCoverageForm.tsx

Fixes EASY-
* change various textual elements

EASY-2218: various textual changes

---

src/main/typescript/components/Footer.tsx

Fixes EASY-2156
* correct DANS `newsletter link`
easy-dtap                      | [PR#349](https://github.com/DANS-KNAW/easy-dtap/pull/349) 
easy-app                      | [PR#141](https://github.com/DANS-KNAW/easy-app/pull/141)

EASY-2156: Newsletter links in footer aanpassen

---

src/main/typescript/lib/formComponents/ContributorFieldArray.tsx

NO JIRA
* Replace random name in help hint of Contributor field with generic help 
* Make captilalization of "Organisation" help hint conform other help hints.

NO JIRA. Replaced help hints with more generic ones

---

src/main/typescript/model/Deposits.ts
src/main/typescript/model/HelpTexts.ts
src/main/typescript/reducers/depositOverviewReducer.ts
src/main/typescript/reducers/fileOverviewReducer.ts
src/main/typescript/reducers/helpTextReducer.ts

Fixes EASY-2252
* no longer use immutable.del for removing a field from an object

EASY-2252: fix file uploading, deleting and re-uploading causes the delete button to be shown

---

src/main/resources/constants/contributorIds.json
src/main/typescript/lib/dropdown/dropdown.ts
src/main/typescript/middleware/depositFormMiddleware.ts
src/main/typescript/model/DropdownLists.ts

Fixes EASY-2219
* replace contributorId field values based on configured regexps
See the JIRA issue for a screenrecording of the result

EASY-2219: replace contributorId field values based on configured regexps

---

src/main/typescript/components/form/DepositFormPage.tsx

Fixes EASY-2294
* change the instruction URLs on the intro pages of easy-webui

EASY-2294: set new instruction URLs

---

src/main/typescript/actions/depositFormActions.ts
src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/lib/fetch.ts
src/main/typescript/middleware/fetchConvertMiddleware.ts

Fixes EASY-2286
* remove TODOs and corresponding console.log statements

EASY-2286: remove TODOs and console.log statements

---

src/main/resources/css/dansColors.css
src/main/resources/css/form.css
src/main/typescript/actions/fileOverviewActions.ts
src/main/typescript/components/Header.tsx
src/main/typescript/components/form/parts/MessageForDataManagerForm.tsx
src/main/typescript/lib/metadata/Metadata.ts
webpack/dev.config.js

Fixes EASY-2288
* remove TODOs and clean up around it when appropriate

EASY-2288: remove old TODOs

---

src/main/typescript/components/form/Validation.ts
src/test/typescript/component/form/Validation.spec.ts

~Fixes EASY-~
* validate the DAI checksum digit

NO-JIRA: Validate DAI checksum digit

---

src/main/typescript/actions/helpTextActions.ts
src/main/typescript/components/form/parts/PrivacySensitiveDataForm.tsx
src/main/typescript/constants/helpTextConstants.ts
src/main/typescript/lib/formComponents/HelpText.tsx
src/main/typescript/reducers/helpTextReducer.ts

~Fixes EASY-~
* Make 'personal data' question bold
* Simplify HelpText component and remove unnecessary registration

NO-JIRA: Minor changes

---

src/main/resources/helptexts/accessRights.html
src/main/resources/helptexts/privacySensitiveDataPresent.html
src/main/resources/helptexts/uploadFiles.html
src/main/typescript/actions/dropdownActions.ts
src/main/typescript/components/form/parts/PrivacySensitiveDataForm.tsx
src/main/typescript/lib/metadata/License.ts

Fixes EASY-2408
* adjust help texts
* adjust display texts
* (besides the issue) remove the dans-license from the list of Open Access licenses
* (besides the issue) `LICENSE` to `LICENCE`

EASY-2408: adjust help texts

---

src/main/typescript/components/form/parts/DepositLicenseForm.tsx

Fixes EASY-2210
* Link to Deposit Agreement on DANS website

EASY-2201: Link to Deposit Agreement on DANS website

---

pom.xml
src/main/typescript/lib/metadata/License.ts
src/test/typescript/lib/metadata/License.spec.ts
src/test/typescript/mockserver/metadata.ts

EASY-2211: link to new license

---

src/main/typescript/components/form/parts/DepositLicenseForm.tsx

Fixes EASY-2439
* Make some changes in the UI texts related to legal matters.

EASY-2439 changes to legal texts in UI

---

package-lock.json
pom.xml

Fixes EASY-2209: upgrade easy-licenses
* 
* 
* 
https://github.com/DANS-KNAW/easy-deposit-agreement-creator/pull/59

EASY-2209: upgrade easy-licenses

---

docs/validation.md
src/main/typescript/components/form/Validation.ts
src/test/typescript/component/form/Validation.spec.ts

Fixes EASY-2045: Synchronize docs and error messages

---

src/main/resources/helptexts/contributors.html
src/main/typescript/components/form/parts/DepositLicenseForm.tsx

* Examples were swapped.
* Also, adjusted depositor agreement acceptance text.

NO JIRA. Correct examples for ORCID and ISNI.

---

src/main/resources/css/form.css
src/main/typescript/lib/formComponents/ContributorFieldArray.tsx
src/main/typescript/lib/formComponents/LabeledTextField.tsx
src/main/typescript/lib/formComponents/SchemedBoxArray.tsx
src/main/typescript/lib/formComponents/SchemedPointArray.tsx
src/main/typescript/lib/formComponents/TextField.tsx

Fixes EASY-2486
* display validation errors for contributor identifier fields
* fix warnings about non-unique ids in CSS

EASY-2486: Display validation errors for contributor identifier fields

---

src/main/typescript/actions/depositFormActions.ts
src/main/typescript/actions/fileOverviewActions.ts
src/main/typescript/components/form/DepositForm.tsx
src/main/typescript/components/form/parts/fileUpload/overview/FilesOverview.tsx
src/main/typescript/components/form/parts/fileUpload/upload/FileLoader.tsx
src/main/typescript/components/form/parts/fileUpload/upload/FileUploader.tsx
src/main/typescript/middleware/depositFormMiddleware.ts

Fixes EASY-2487
* set state from REJECTED to DRAFT on file upload and delete

EASY-2487: set state from REJECTED to DRAFT on file upload and delete

---

src/main/resources/helptexts/license.html
src/main/resources/helptexts/privacySensitiveDataPresent.html
src/main/resources/helptexts/rightsHolders.html

Fixes EASY-2491
* improve help texts

EASY-2491: help text improvements

---

src/main/resources/helptexts/dates.html

NO JIRA. Typo in help text.

---

src/main/typescript/lib/metadata/Metadata.ts
src/main/typescript/lib/metadata/Relation.ts
src/test/typescript/lib/metadata/Metadata.spec.ts
src/test/typescript/lib/metadata/Relation.spec.ts
src/test/typescript/mockserver/metadata.ts

Fixes EASY-2545
* simplify conversion of relations

EASY-2545: simplify conversion of relations

---

src/main/typescript/components/form/parts/BasicInformationForm.tsx

~Fixes EASY-~
* improve the hint text on the 'free date' fields (based on an email exchange with @janvanmansum)

improve the hint text on the 'free date' fields

---

src/main/typescript/components/form/parts/BasicInformationForm.tsx
src/main/typescript/lib/formComponents/DatePickerField.tsx

Fixes EASY-2583
* improve UX for DatePicker fields

EASY-2583: improve UX for DatePicker fields

---

src/main/resources/css/depositForm.css
src/main/resources/css/depositOverviewPage.css
src/main/resources/css/filesOverviewTable.css

Fixes EASY-2606
* change css styling fix for tables to be more specific, in order to fix broken help text tables.

EASY-2606: fix for ie11 tables

---

src/main/typescript/components/form/DepositResourceLoader.tsx

Part of preparation for EASY-2529
* fixing bug introduced in https://github.com/DANS-KNAW/easy-deposit-ui/pull/239 of unmounting and remounting form on deposit state change

EASY-2529: fixing bug of unmounting and remounting form on deposit state change

---

src/main/typescript/components/form/Validation.tsx
src/test/typescript/component/form/Validation.spec.ts

Fixes EASY-2719
* implement stricter validation for creators and contributors

EASY-2719: stricter validation for creators and contributors
